// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/faridlan/omni-library-api/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// BookNoteUsecase is an autogenerated mock type for the BookNoteUsecase type
type BookNoteUsecase struct {
	mock.Mock
}

// AddNote provides a mock function with given fields: ctx, note
func (_m *BookNoteUsecase) AddNote(ctx context.Context, note *domain.BookNote) error {
	ret := _m.Called(ctx, note)

	if len(ret) == 0 {
		panic("no return value specified for AddNote")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.BookNote) error); ok {
		r0 = rf(ctx, note)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetNotesForBook provides a mock function with given fields: ctx, userBookID
func (_m *BookNoteUsecase) GetNotesForBook(ctx context.Context, userBookID string) ([]*domain.BookNote, error) {
	ret := _m.Called(ctx, userBookID)

	if len(ret) == 0 {
		panic("no return value specified for GetNotesForBook")
	}

	var r0 []*domain.BookNote
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*domain.BookNote, error)); ok {
		return rf(ctx, userBookID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*domain.BookNote); ok {
		r0 = rf(ctx, userBookID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.BookNote)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userBookID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewBookNoteUsecase creates a new instance of BookNoteUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBookNoteUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *BookNoteUsecase {
	mock := &BookNoteUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
