// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/faridlan/omni-library-api/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// BookUsecase is an autogenerated mock type for the BookUsecase type
type BookUsecase struct {
	mock.Mock
}

// CreateManual provides a mock function with given fields: ctx, book
func (_m *BookUsecase) CreateManual(ctx context.Context, book *domain.Book) (*domain.Book, error) {
	ret := _m.Called(ctx, book)

	if len(ret) == 0 {
		panic("no return value specified for CreateManual")
	}

	var r0 *domain.Book
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Book) (*domain.Book, error)); ok {
		return rf(ctx, book)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Book) *domain.Book); ok {
		r0 = rf(ctx, book)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Book)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Book) error); ok {
		r1 = rf(ctx, book)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteBook provides a mock function with given fields: ctx, id
func (_m *BookUsecase) DeleteBook(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBook")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FetchAndSaveMetadata provides a mock function with given fields: ctx, isbn
func (_m *BookUsecase) FetchAndSaveMetadata(ctx context.Context, isbn string) (*domain.Book, error) {
	ret := _m.Called(ctx, isbn)

	if len(ret) == 0 {
		panic("no return value specified for FetchAndSaveMetadata")
	}

	var r0 *domain.Book
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Book, error)); ok {
		return rf(ctx, isbn)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Book); ok {
		r0 = rf(ctx, isbn)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Book)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, isbn)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllBooks provides a mock function with given fields: ctx
func (_m *BookUsecase) GetAllBooks(ctx context.Context) ([]*domain.Book, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllBooks")
	}

	var r0 []*domain.Book
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*domain.Book, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*domain.Book); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Book)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateBook provides a mock function with given fields: ctx, id, req
func (_m *BookUsecase) UpdateBook(ctx context.Context, id string, req *domain.Book) (*domain.Book, error) {
	ret := _m.Called(ctx, id, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBook")
	}

	var r0 *domain.Book
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *domain.Book) (*domain.Book, error)); ok {
		return rf(ctx, id, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *domain.Book) *domain.Book); ok {
		r0 = rf(ctx, id, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Book)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *domain.Book) error); ok {
		r1 = rf(ctx, id, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewBookUsecase creates a new instance of BookUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBookUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *BookUsecase {
	mock := &BookUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
