// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/faridlan/omni-library-api/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// BookMetadataFetcher is an autogenerated mock type for the BookMetadataFetcher type
type BookMetadataFetcher struct {
	mock.Mock
}

// FetchByISBN provides a mock function with given fields: ctx, isbn
func (_m *BookMetadataFetcher) FetchByISBN(ctx context.Context, isbn string) (*domain.Book, error) {
	ret := _m.Called(ctx, isbn)

	if len(ret) == 0 {
		panic("no return value specified for FetchByISBN")
	}

	var r0 *domain.Book
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Book, error)); ok {
		return rf(ctx, isbn)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Book); ok {
		r0 = rf(ctx, isbn)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Book)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, isbn)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewBookMetadataFetcher creates a new instance of BookMetadataFetcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBookMetadataFetcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *BookMetadataFetcher {
	mock := &BookMetadataFetcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
