// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/faridlan/omni-library-api/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// BookNoteRepository is an autogenerated mock type for the BookNoteRepository type
type BookNoteRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, note
func (_m *BookNoteRepository) Create(ctx context.Context, note *domain.BookNote) error {
	ret := _m.Called(ctx, note)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.BookNote) error); ok {
		r0 = rf(ctx, note)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByUserBookID provides a mock function with given fields: ctx, userBookID, params
func (_m *BookNoteRepository) GetByUserBookID(ctx context.Context, userBookID string, params domain.PaginationQuery) ([]*domain.BookNote, int64, error) {
	ret := _m.Called(ctx, userBookID, params)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserBookID")
	}

	var r0 []*domain.BookNote
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.PaginationQuery) ([]*domain.BookNote, int64, error)); ok {
		return rf(ctx, userBookID, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.PaginationQuery) []*domain.BookNote); ok {
		r0 = rf(ctx, userBookID, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.BookNote)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, domain.PaginationQuery) int64); ok {
		r1 = rf(ctx, userBookID, params)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, domain.PaginationQuery) error); ok {
		r2 = rf(ctx, userBookID, params)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewBookNoteRepository creates a new instance of BookNoteRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBookNoteRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *BookNoteRepository {
	mock := &BookNoteRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
