// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/faridlan/omni-library-api/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// UserBookRepository is an autogenerated mock type for the UserBookRepository type
type UserBookRepository struct {
	mock.Mock
}

// AddBookToShelf provides a mock function with given fields: ctx, ub
func (_m *UserBookRepository) AddBookToShelf(ctx context.Context, ub *domain.UserBook) error {
	ret := _m.Called(ctx, ub)

	if len(ret) == 0 {
		panic("no return value specified for AddBookToShelf")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.UserBook) error); ok {
		r0 = rf(ctx, ub)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, userID, bookID
func (_m *UserBookRepository) Delete(ctx context.Context, userID string, bookID string) error {
	ret := _m.Called(ctx, userID, bookID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, bookID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByBookID provides a mock function with given fields: ctx, userID, bookID
func (_m *UserBookRepository) GetByBookID(ctx context.Context, userID string, bookID string) (*domain.UserBookWithMetadata, error) {
	ret := _m.Called(ctx, userID, bookID)

	if len(ret) == 0 {
		panic("no return value specified for GetByBookID")
	}

	var r0 *domain.UserBookWithMetadata
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*domain.UserBookWithMetadata, error)); ok {
		return rf(ctx, userID, bookID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *domain.UserBookWithMetadata); ok {
		r0 = rf(ctx, userID, bookID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserBookWithMetadata)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, bookID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *UserBookRepository) GetByID(ctx context.Context, id string) (*domain.UserBook, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.UserBook
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.UserBook, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.UserBook); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserBook)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByUserAndBookID provides a mock function with given fields: ctx, userID, bookID
func (_m *UserBookRepository) GetByUserAndBookID(ctx context.Context, userID string, bookID string) (*domain.UserBookWithMetadata, error) {
	ret := _m.Called(ctx, userID, bookID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserAndBookID")
	}

	var r0 *domain.UserBookWithMetadata
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*domain.UserBookWithMetadata, error)); ok {
		return rf(ctx, userID, bookID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *domain.UserBookWithMetadata); ok {
		r0 = rf(ctx, userID, bookID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserBookWithMetadata)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, bookID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByUserID provides a mock function with given fields: ctx, userID, status, params
func (_m *UserBookRepository) GetByUserID(ctx context.Context, userID string, status string, params domain.PaginationQuery) ([]*domain.UserBookWithMetadata, int64, error) {
	ret := _m.Called(ctx, userID, status, params)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserID")
	}

	var r0 []*domain.UserBookWithMetadata
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, domain.PaginationQuery) ([]*domain.UserBookWithMetadata, int64, error)); ok {
		return rf(ctx, userID, status, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, domain.PaginationQuery) []*domain.UserBookWithMetadata); ok {
		r0 = rf(ctx, userID, status, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.UserBookWithMetadata)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, domain.PaginationQuery) int64); ok {
		r1 = rf(ctx, userID, status, params)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string, domain.PaginationQuery) error); ok {
		r2 = rf(ctx, userID, status, params)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// UpdateProgress provides a mock function with given fields: ctx, ub
func (_m *UserBookRepository) UpdateProgress(ctx context.Context, ub *domain.UserBook) error {
	ret := _m.Called(ctx, ub)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProgress")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.UserBook) error); ok {
		r0 = rf(ctx, ub)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewUserBookRepository creates a new instance of UserBookRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserBookRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserBookRepository {
	mock := &UserBookRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
