// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/faridlan/omni-library-api/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// UserBookRepository is an autogenerated mock type for the UserBookRepository type
type UserBookRepository struct {
	mock.Mock
}

// AddBookToShelf provides a mock function with given fields: ctx, ub
func (_m *UserBookRepository) AddBookToShelf(ctx context.Context, ub *domain.UserBook) error {
	ret := _m.Called(ctx, ub)

	if len(ret) == 0 {
		panic("no return value specified for AddBookToShelf")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.UserBook) error); ok {
		r0 = rf(ctx, ub)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByID provides a mock function with given fields: ctx, userID
func (_m *UserBookRepository) GetByID(ctx context.Context, userID string) (*domain.UserBook, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.UserBook
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.UserBook, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.UserBook); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserBook)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByUserAndBookID provides a mock function with given fields: ctx, userID, bookID
func (_m *UserBookRepository) GetByUserAndBookID(ctx context.Context, userID string, bookID string) (*domain.UserBook, error) {
	ret := _m.Called(ctx, userID, bookID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserAndBookID")
	}

	var r0 *domain.UserBook
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*domain.UserBook, error)); ok {
		return rf(ctx, userID, bookID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *domain.UserBook); ok {
		r0 = rf(ctx, userID, bookID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserBook)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, bookID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByUserID provides a mock function with given fields: ctx, userID, status
func (_m *UserBookRepository) GetByUserID(ctx context.Context, userID string, status string) ([]*domain.UserBookWithMetadata, error) {
	ret := _m.Called(ctx, userID, status)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserID")
	}

	var r0 []*domain.UserBookWithMetadata
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]*domain.UserBookWithMetadata, error)); ok {
		return rf(ctx, userID, status)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []*domain.UserBookWithMetadata); ok {
		r0 = rf(ctx, userID, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.UserBookWithMetadata)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateProgress provides a mock function with given fields: ctx, ub
func (_m *UserBookRepository) UpdateProgress(ctx context.Context, ub *domain.UserBook) error {
	ret := _m.Called(ctx, ub)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProgress")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.UserBook) error); ok {
		r0 = rf(ctx, ub)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewUserBookRepository creates a new instance of UserBookRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserBookRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserBookRepository {
	mock := &UserBookRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
