// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/faridlan/omni-library-api/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// UserBookUsecase is an autogenerated mock type for the UserBookUsecase type
type UserBookUsecase struct {
	mock.Mock
}

// GetUserBookDetail provides a mock function with given fields: ctx, userID, bookID
func (_m *UserBookUsecase) GetUserBookDetail(ctx context.Context, userID string, bookID string) (*domain.UserBookWithMetadata, error) {
	ret := _m.Called(ctx, userID, bookID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserBookDetail")
	}

	var r0 *domain.UserBookWithMetadata
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*domain.UserBookWithMetadata, error)); ok {
		return rf(ctx, userID, bookID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *domain.UserBookWithMetadata); ok {
		r0 = rf(ctx, userID, bookID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserBookWithMetadata)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, bookID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserLibrary provides a mock function with given fields: ctx, userID, status, params
func (_m *UserBookUsecase) GetUserLibrary(ctx context.Context, userID string, status string, params domain.PaginationQuery) ([]*domain.UserBookWithMetadata, domain.PaginationMeta, error) {
	ret := _m.Called(ctx, userID, status, params)

	if len(ret) == 0 {
		panic("no return value specified for GetUserLibrary")
	}

	var r0 []*domain.UserBookWithMetadata
	var r1 domain.PaginationMeta
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, domain.PaginationQuery) ([]*domain.UserBookWithMetadata, domain.PaginationMeta, error)); ok {
		return rf(ctx, userID, status, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, domain.PaginationQuery) []*domain.UserBookWithMetadata); ok {
		r0 = rf(ctx, userID, status, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.UserBookWithMetadata)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, domain.PaginationQuery) domain.PaginationMeta); ok {
		r1 = rf(ctx, userID, status, params)
	} else {
		r1 = ret.Get(1).(domain.PaginationMeta)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string, domain.PaginationQuery) error); ok {
		r2 = rf(ctx, userID, status, params)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// TrackNewBook provides a mock function with given fields: ctx, userID, bookID
func (_m *UserBookUsecase) TrackNewBook(ctx context.Context, userID string, bookID string) (*domain.UserBook, error) {
	ret := _m.Called(ctx, userID, bookID)

	if len(ret) == 0 {
		panic("no return value specified for TrackNewBook")
	}

	var r0 *domain.UserBook
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*domain.UserBook, error)); ok {
		return rf(ctx, userID, bookID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *domain.UserBook); ok {
		r0 = rf(ctx, userID, bookID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserBook)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, bookID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateReadingStatus provides a mock function with given fields: ctx, userID, bookID, status, page, rating
func (_m *UserBookUsecase) UpdateReadingStatus(ctx context.Context, userID string, bookID string, status string, page int, rating int) (*domain.UserBook, error) {
	ret := _m.Called(ctx, userID, bookID, status, page, rating)

	if len(ret) == 0 {
		panic("no return value specified for UpdateReadingStatus")
	}

	var r0 *domain.UserBook
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, int, int) (*domain.UserBook, error)); ok {
		return rf(ctx, userID, bookID, status, page, rating)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, int, int) *domain.UserBook); ok {
		r0 = rf(ctx, userID, bookID, status, page, rating)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserBook)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, int, int) error); ok {
		r1 = rf(ctx, userID, bookID, status, page, rating)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUserBookUsecase creates a new instance of UserBookUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserBookUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserBookUsecase {
	mock := &UserBookUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
