name: OmniLibrary CI/CD

on:
  push:
    branches: [ "main", "stag" ]
    tags: [ "v*.*.*" ]
  pull_request:
    branches: [ "main", "stag" ]

jobs:
  test:
    name: Unit Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'

      - name: Run Tests
        run: go test -v ./internal/usecase/... ./internal/utils/...

  build-and-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push'
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set Image Tag
        run: |
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            # Mengambil v1.0.0 menjadi 1.0.0
            VERSION=${GITHUB_REF#refs/tags/v}
            echo "IMAGE_TAG=$VERSION" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "IMAGE_TAG=latest" >> $GITHUB_ENV
          else
            echo "IMAGE_TAG=staging" >> $GITHUB_ENV
          fi

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/omni-api:${{ env.IMAGE_TAG }}

  deploy-staging:
    name: Deploy to Azure Staging
    runs-on: ubuntu-latest
    needs: build-and-push
    # PENTING: Job ini HANYA akan dieksekusi jika push terjadi di branch 'stag'
    if: github.ref == 'refs/heads/stag'
    
    steps:
      - name: Execute SSH Commands on Azure VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: ${{ secrets.AZURE_USERNAME }}
          key: ${{ secrets.AZURE_KEY }}
          script: |
            echo "Memasuki ruang Staging..."
            cd ~/omnilibrary/stag
            
            echo "Menarik image terbaru dari Docker Hub..."
            sudo docker-compose pull
            
            echo "Me-restart container Staging..."
            sudo docker-compose up -d
            
            echo "Deployment Staging Selesai! 🚀"